# permissions for end users to edit sonarqubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sonarqube-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonarqube
    app.kubernetes.io/part-of: sonarqube
    app.kubernetes.io/managed-by: kustomize
  name: sonarqube-editor-role
rules:
- apiGroups:
  - cache.sonarqube
  resources:
  - sonarqubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.sonarqube
  resources:
  - sonarqubes/status
  verbs:
  - get
